package com.itany.mapper;

import com.itany.entity.Examine;
import com.itany.entity.ExamineExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ExamineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbggenerated Sat Dec 14 16:25:03 CST 2024
     */
    int countByExample(ExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbggenerated Sat Dec 14 16:25:03 CST 2024
     */
    int deleteByExample(ExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbggenerated Sat Dec 14 16:25:03 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbggenerated Sat Dec 14 16:25:03 CST 2024
     */
    int insert(Examine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbggenerated Sat Dec 14 16:25:03 CST 2024
     */
    int insertSelective(Examine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbggenerated Sat Dec 14 16:25:03 CST 2024
     */
    List<Examine> selectByExample(ExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbggenerated Sat Dec 14 16:25:03 CST 2024
     */
    Examine selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbggenerated Sat Dec 14 16:25:03 CST 2024
     */
    int updateByExampleSelective(@Param("record") Examine record, @Param("example") ExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbggenerated Sat Dec 14 16:25:03 CST 2024
     */
    int updateByExample(@Param("record") Examine record, @Param("example") ExamineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbggenerated Sat Dec 14 16:25:03 CST 2024
     */
    int updateByPrimaryKeySelective(Examine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_examine
     *
     * @mbggenerated Sat Dec 14 16:25:03 CST 2024
     */
    int updateByPrimaryKey(Examine record);

    List<Examine> selectExamineWithUser(Examine examine);
}