package com.itany.mapper;


import com.itany.entity.ServerCompany;
import com.itany.entity.ServerCompanyExample;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface ServerCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server_commpany
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    Integer countByExample(ServerCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server_commpany
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    Integer deleteByExample(ServerCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server_commpany
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    Integer deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server_commpany
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    Integer insert(ServerCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server_commpany
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    Integer insertSelective(ServerCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server_commpany
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    List<ServerCompany> selectByExample(ServerCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server_commpany
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    ServerCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server_commpany
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    Integer updateByExampleSelective(@Param("record") ServerCompany record, @Param("example") ServerCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server_commpany
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    Integer updateByExample(@Param("record") ServerCompany record, @Param("example") ServerCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server_commpany
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    Integer updateByPrimaryKeySelective(ServerCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_server_commpany
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    Integer updateByPrimaryKey(ServerCompany record);


    List<ServerCompany> selectServerCompanyWithUsersAndMembers(
            @Param("id") Integer id,
            @Param("name") String name,
            @Param("phone") String phone,
            @Param("flag") Integer flag,
            @Param("type") Integer type,
            @Param("level") String level,
            @Param("currentDate") Date currentDate
    );

    void updateServerCompanyFlag(ServerCompany serverCompany);
}