package com.itany.entity;

public class Annex {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annex.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annex.path
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annex.filename
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annex.type
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annex.keyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer keyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_annex.tabletype
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer tabletype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annex.id
     *
     * @return the value of t_annex.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annex.id
     *
     * @param id the value for t_annex.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annex.path
     *
     * @return the value of t_annex.path
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annex.path
     *
     * @param path the value for t_annex.path
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annex.filename
     *
     * @return the value of t_annex.filename
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annex.filename
     *
     * @param filename the value for t_annex.filename
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annex.type
     *
     * @return the value of t_annex.type
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annex.type
     *
     * @param type the value for t_annex.type
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annex.keyid
     *
     * @return the value of t_annex.keyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getKeyid() {
        return keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annex.keyid
     *
     * @param keyid the value for t_annex.keyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setKeyid(Integer keyid) {
        this.keyid = keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_annex.tabletype
     *
     * @return the value of t_annex.tabletype
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getTabletype() {
        return tabletype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_annex.tabletype
     *
     * @param tabletype the value for t_annex.tabletype
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setTabletype(Integer tabletype) {
        this.tabletype = tabletype;
    }
}