package com.itany.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Examine implements Serializable {
    private static final long serialVersionUID = 1L;

    private User user;

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.title
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.name
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.typeid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.createdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.linkman
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.phone
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.userid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.commpanycreatedate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Date commpanycreatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.address
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.scale
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String scale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.gps
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String gps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.examinetype
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer examinetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.flag
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.servertype
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String servertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.serverarea
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String serverarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.info
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.commpanyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer commpanyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.examine_info
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String examineInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_examine.price
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.id
     *
     * @return the value of t_examine.id
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.id
     *
     * @param id the value for t_examine.id
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.title
     *
     * @return the value of t_examine.title
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.title
     *
     * @param title the value for t_examine.title
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.name
     *
     * @return the value of t_examine.name
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.name
     *
     * @param name the value for t_examine.name
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.typeid
     *
     * @return the value of t_examine.typeid
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.typeid
     *
     * @param typeid the value for t_examine.typeid
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.createdate
     *
     * @return the value of t_examine.createdate
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.createdate
     *
     * @param createdate the value for t_examine.createdate
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.linkman
     *
     * @return the value of t_examine.linkman
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.linkman
     *
     * @param linkman the value for t_examine.linkman
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.phone
     *
     * @return the value of t_examine.phone
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.phone
     *
     * @param phone the value for t_examine.phone
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.userid
     *
     * @return the value of t_examine.userid
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.userid
     *
     * @param userid the value for t_examine.userid
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.commpanycreatedate
     *
     * @return the value of t_examine.commpanycreatedate
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Date getCommpanycreatedate() {
        return commpanycreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.commpanycreatedate
     *
     * @param commpanycreatedate the value for t_examine.commpanycreatedate
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setCommpanycreatedate(Date commpanycreatedate) {
        this.commpanycreatedate = commpanycreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.address
     *
     * @return the value of t_examine.address
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.address
     *
     * @param address the value for t_examine.address
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.scale
     *
     * @return the value of t_examine.scale
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.scale
     *
     * @param scale the value for t_examine.scale
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setScale(String scale) {
        this.scale = scale == null ? null : scale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.gps
     *
     * @return the value of t_examine.gps
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getGps() {
        return gps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.gps
     *
     * @param gps the value for t_examine.gps
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setGps(String gps) {
        this.gps = gps == null ? null : gps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.examinetype
     *
     * @return the value of t_examine.examinetype
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getExaminetype() {
        return examinetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.examinetype
     *
     * @param examinetype the value for t_examine.examinetype
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setExaminetype(Integer examinetype) {
        this.examinetype = examinetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.flag
     *
     * @return the value of t_examine.flag
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.flag
     *
     * @param flag the value for t_examine.flag
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.servertype
     *
     * @return the value of t_examine.servertype
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getServertype() {
        return servertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.servertype
     *
     * @param servertype the value for t_examine.servertype
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setServertype(String servertype) {
        this.servertype = servertype == null ? null : servertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.serverarea
     *
     * @return the value of t_examine.serverarea
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getServerarea() {
        return serverarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.serverarea
     *
     * @param serverarea the value for t_examine.serverarea
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setServerarea(String serverarea) {
        this.serverarea = serverarea == null ? null : serverarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.info
     *
     * @return the value of t_examine.info
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.info
     *
     * @param info the value for t_examine.info
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.commpanyid
     *
     * @return the value of t_examine.commpanyid
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getCommpanyid() {
        return commpanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.commpanyid
     *
     * @param commpanyid the value for t_examine.commpanyid
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setCommpanyid(Integer commpanyid) {
        this.commpanyid = commpanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.examine_info
     *
     * @return the value of t_examine.examine_info
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getExamineInfo() {
        return examineInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.examine_info
     *
     * @param examineInfo the value for t_examine.examine_info
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setExamineInfo(String examineInfo) {
        this.examineInfo = examineInfo == null ? null : examineInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_examine.price
     *
     * @return the value of t_examine.price
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_examine.price
     *
     * @param price the value for t_examine.price
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}