package com.itany.entity;

public class ManagerUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_user.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_user.username
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_user.password
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_manager_user.commpanyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer commpanyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_user.id
     *
     * @return the value of t_manager_user.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_user.id
     *
     * @param id the value for t_manager_user.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_user.username
     *
     * @return the value of t_manager_user.username
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_user.username
     *
     * @param username the value for t_manager_user.username
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_user.password
     *
     * @return the value of t_manager_user.password
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_user.password
     *
     * @param password the value for t_manager_user.password
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_manager_user.commpanyid
     *
     * @return the value of t_manager_user.commpanyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getCommpanyid() {
        return commpanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_manager_user.commpanyid
     *
     * @param commpanyid the value for t_manager_user.commpanyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setCommpanyid(Integer commpanyid) {
        this.commpanyid = commpanyid;
    }
}