package com.itany.entity;

import java.util.Date;

public class MemberCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_commpany.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_commpany.memberid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer memberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_commpany.commpanyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer commpanyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_commpany.startdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Date startdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_commpany.enddate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Date enddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_commpany.flag
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member_commpany.no
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String no;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_commpany.id
     *
     * @return the value of t_member_commpany.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_commpany.id
     *
     * @param id the value for t_member_commpany.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_commpany.memberid
     *
     * @return the value of t_member_commpany.memberid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getMemberid() {
        return memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_commpany.memberid
     *
     * @param memberid the value for t_member_commpany.memberid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setMemberid(Integer memberid) {
        this.memberid = memberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_commpany.commpanyid
     *
     * @return the value of t_member_commpany.commpanyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getCommpanyid() {
        return commpanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_commpany.commpanyid
     *
     * @param commpanyid the value for t_member_commpany.commpanyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setCommpanyid(Integer commpanyid) {
        this.commpanyid = commpanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_commpany.startdate
     *
     * @return the value of t_member_commpany.startdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_commpany.startdate
     *
     * @param startdate the value for t_member_commpany.startdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_commpany.enddate
     *
     * @return the value of t_member_commpany.enddate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_commpany.enddate
     *
     * @param enddate the value for t_member_commpany.enddate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_commpany.flag
     *
     * @return the value of t_member_commpany.flag
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_commpany.flag
     *
     * @param flag the value for t_member_commpany.flag
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member_commpany.no
     *
     * @return the value of t_member_commpany.no
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member_commpany.no
     *
     * @param no the value for t_member_commpany.no
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setNo(String no) {
        this.no = no == null ? null : no.trim();
    }
}