package com.itany.entity;

public class Member {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.level
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.price
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_member.day
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String day;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.id
     *
     * @return the value of t_member.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.id
     *
     * @param id the value for t_member.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.level
     *
     * @return the value of t_member.level
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.level
     *
     * @param level the value for t_member.level
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.price
     *
     * @return the value of t_member.price
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.price
     *
     * @param price the value for t_member.price
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_member.day
     *
     * @return the value of t_member.day
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_member.day
     *
     * @param day the value for t_member.day
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setDay(String day) {
        this.day = day == null ? null : day.trim();
    }
}