package com.itany.entity;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.name
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.msg
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.phone
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.area
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.commpanyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer commpanyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_message.createdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.id
     *
     * @return the value of t_message.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.id
     *
     * @param id the value for t_message.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.name
     *
     * @return the value of t_message.name
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.name
     *
     * @param name the value for t_message.name
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.msg
     *
     * @return the value of t_message.msg
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.msg
     *
     * @param msg the value for t_message.msg
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.phone
     *
     * @return the value of t_message.phone
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.phone
     *
     * @param phone the value for t_message.phone
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.area
     *
     * @return the value of t_message.area
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.area
     *
     * @param area the value for t_message.area
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.commpanyid
     *
     * @return the value of t_message.commpanyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getCommpanyid() {
        return commpanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.commpanyid
     *
     * @param commpanyid the value for t_message.commpanyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setCommpanyid(Integer commpanyid) {
        this.commpanyid = commpanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_message.createdate
     *
     * @return the value of t_message.createdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_message.createdate
     *
     * @param createdate the value for t_message.createdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}