package com.itany.entity;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.title
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.info
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.manageruserid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer manageruserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.userid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.flag
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.createdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.id
     *
     * @return the value of t_notice.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.id
     *
     * @param id the value for t_notice.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.title
     *
     * @return the value of t_notice.title
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.title
     *
     * @param title the value for t_notice.title
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.info
     *
     * @return the value of t_notice.info
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.info
     *
     * @param info the value for t_notice.info
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.manageruserid
     *
     * @return the value of t_notice.manageruserid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getManageruserid() {
        return manageruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.manageruserid
     *
     * @param manageruserid the value for t_notice.manageruserid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setManageruserid(Integer manageruserid) {
        this.manageruserid = manageruserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.userid
     *
     * @return the value of t_notice.userid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.userid
     *
     * @param userid the value for t_notice.userid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.flag
     *
     * @return the value of t_notice.flag
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.flag
     *
     * @param flag the value for t_notice.flag
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.createdate
     *
     * @return the value of t_notice.createdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.createdate
     *
     * @param createdate the value for t_notice.createdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}