package com.itany.entity;

import java.util.Date;

public class ServerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_info.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_info.servername
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String servername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_info.info
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_info.linkman
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_info.phone
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_info.userid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_info.commpanyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer commpanyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_info.createdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_info.flag
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_info.price
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_info.id
     *
     * @return the value of t_server_info.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_info.id
     *
     * @param id the value for t_server_info.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_info.servername
     *
     * @return the value of t_server_info.servername
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getServername() {
        return servername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_info.servername
     *
     * @param servername the value for t_server_info.servername
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setServername(String servername) {
        this.servername = servername == null ? null : servername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_info.info
     *
     * @return the value of t_server_info.info
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_info.info
     *
     * @param info the value for t_server_info.info
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_info.linkman
     *
     * @return the value of t_server_info.linkman
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_info.linkman
     *
     * @param linkman the value for t_server_info.linkman
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_info.phone
     *
     * @return the value of t_server_info.phone
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_info.phone
     *
     * @param phone the value for t_server_info.phone
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_info.userid
     *
     * @return the value of t_server_info.userid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_info.userid
     *
     * @param userid the value for t_server_info.userid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_info.commpanyid
     *
     * @return the value of t_server_info.commpanyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getCommpanyid() {
        return commpanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_info.commpanyid
     *
     * @param commpanyid the value for t_server_info.commpanyid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setCommpanyid(Integer commpanyid) {
        this.commpanyid = commpanyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_info.createdate
     *
     * @return the value of t_server_info.createdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_info.createdate
     *
     * @param createdate the value for t_server_info.createdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_info.flag
     *
     * @return the value of t_server_info.flag
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_info.flag
     *
     * @param flag the value for t_server_info.flag
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_info.price
     *
     * @return the value of t_server_info.price
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_info.price
     *
     * @param price the value for t_server_info.price
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }
}