package com.itany.entity;

public class ServerArea {

    public ServerArea() {
    }

    public ServerArea(Integer serverid, Integer areaid) {
        this.serverid = serverid;
        this.areaid = areaid;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_area.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_area.serverid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer serverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_area.areaid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer areaid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_area.id
     *
     * @return the value of t_server_area.id
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_area.id
     *
     * @param id the value for t_server_area.id
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_area.serverid
     *
     * @return the value of t_server_area.serverid
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getServerid() {
        return serverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_area.serverid
     *
     * @param serverid the value for t_server_area.serverid
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setServerid(Integer serverid) {
        this.serverid = serverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_area.areaid
     *
     * @return the value of t_server_area.areaid
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_area.areaid
     *
     * @param areaid the value for t_server_area.areaid
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }
}