package com.itany.entity;

import java.util.Date;

public class ServerCompany {
    private static final long serialVersionUID = 1L;

//    private User user;
//    private MemberCompany memberCompany;
//    private Member member;
//    private UserStats userStats;
//
//    public UserStats getUserStats() {
//        return userStats;
//    }
//
//    public void setUserStats(UserStats userStats) {
//        this.userStats = userStats;
//    }
//
//    public ServerCompany(User user, MemberCompany memberCompany, Member member, UserStats userStats, Integer id, String name, String info, String address, String gps, String scale, Date createdate, Date joindate, Integer flag, Integer type, String linkman, String phone) {
//        this.user = user;
//        this.memberCompany = memberCompany;
//        this.member = member;
//        this.userStats = userStats;
//        this.id = id;
//        this.name = name;
//        this.info = info;
//        this.address = address;
//        this.gps = gps;
//        this.scale = scale;
//        this.createdate = createdate;
//        this.joindate = joindate;
//        this.flag = flag;
//        this.type = type;
//        this.linkman = linkman;
//        this.phone = phone;
//    }

//    public User getUser() {
//        return user;
//    }
//
//    public void setUser(User user) {
//        this.user = user;
//    }
//
//    public MemberCompany getMemberCompany() {
//        return memberCompany;
//    }
//
//    public void setMemberCompany(MemberCompany memberCompany) {
//        this.memberCompany = memberCompany;
//    }
//
//    public Member getMember() {
//        return member;
//    }
//
//    public void setMember(Member member) {
//        this.member = member;
//    }

    @Override
    public String toString() {
        return "ServerCompany{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", info='" + info + '\'' +
                ", address='" + address + '\'' +
                ", gps='" + gps + '\'' +
                ", scale='" + scale + '\'' +
                ", createdate=" + createdate +
                ", joindate=" + joindate +
                ", flag=" + flag +
                ", type=" + type +
                ", linkman='" + linkman + '\'' +
                ", phone='" + phone + '\'' +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_commpany.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_commpany.name
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_commpany.info
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_commpany.address
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_commpany.gps
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String gps;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_commpany.scale
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String scale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_commpany.createdate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_commpany.joindate
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Date joindate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_commpany.flag
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_commpany.type
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_commpany.linkman
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String linkman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_commpany.phone
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_commpany.id
     *
     * @return the value of t_server_commpany.id
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_commpany.id
     *
     * @param id the value for t_server_commpany.id
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_commpany.name
     *
     * @return the value of t_server_commpany.name
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_commpany.name
     *
     * @param name the value for t_server_commpany.name
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_commpany.info
     *
     * @return the value of t_server_commpany.info
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_commpany.info
     *
     * @param info the value for t_server_commpany.info
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_commpany.address
     *
     * @return the value of t_server_commpany.address
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_commpany.address
     *
     * @param address the value for t_server_commpany.address
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_commpany.gps
     *
     * @return the value of t_server_commpany.gps
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getGps() {
        return gps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_commpany.gps
     *
     * @param gps the value for t_server_commpany.gps
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setGps(String gps) {
        this.gps = gps == null ? null : gps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_commpany.scale
     *
     * @return the value of t_server_commpany.scale
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_commpany.scale
     *
     * @param scale the value for t_server_commpany.scale
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setScale(String scale) {
        this.scale = scale == null ? null : scale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_commpany.createdate
     *
     * @return the value of t_server_commpany.createdate
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_commpany.createdate
     *
     * @param createdate the value for t_server_commpany.createdate
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_commpany.joindate
     *
     * @return the value of t_server_commpany.joindate
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Date getJoindate() {
        return joindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_commpany.joindate
     *
     * @param joindate the value for t_server_commpany.joindate
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setJoindate(Date joindate) {
        this.joindate = joindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_commpany.flag
     *
     * @return the value of t_server_commpany.flag
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_commpany.flag
     *
     * @param flag the value for t_server_commpany.flag
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_commpany.type
     *
     * @return the value of t_server_commpany.type
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_commpany.type
     *
     * @param type the value for t_server_commpany.type
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_commpany.linkman
     *
     * @return the value of t_server_commpany.linkman
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_commpany.linkman
     *
     * @param linkman the value for t_server_commpany.linkman
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_commpany.phone
     *
     * @return the value of t_server_commpany.phone
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_commpany.phone
     *
     * @param phone the value for t_server_commpany.phone
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}