package com.itany.entity;

public class ServerType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_type.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_type.typeid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_server_type.serverid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    private Integer serverid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_type.id
     *
     * @return the value of t_server_type.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_type.id
     *
     * @param id the value for t_server_type.id
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_type.typeid
     *
     * @return the value of t_server_type.typeid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_type.typeid
     *
     * @param typeid the value for t_server_type.typeid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_server_type.serverid
     *
     * @return the value of t_server_type.serverid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public Integer getServerid() {
        return serverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_server_type.serverid
     *
     * @param serverid the value for t_server_type.serverid
     *
     * @mbggenerated Sat Dec 14 10:39:12 CST 2024
     */
    public void setServerid(Integer serverid) {
        this.serverid = serverid;
    }
}